In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [3]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [6]:
data = pd.read_csv(r"C:\Users\Zenbook\Desktop\test_energy_data.csv")

In [12]:
data.describe()

,Square Footage,Number of Occupants,Appliances Used,Average Temperature,Energy Consumption
count,100.000000,100.000000,100.000000,100.000000,100.00000
mean,25881.920000,47.230000,26.970000,22.043300,4187.57830
std,13711.075264,29.905526,14.237846,6.957951,832.55985
min,1161.000000,2.000000,1.000000,10.400000,2351.97000
25%,14161.000000,21.000000,16.750000,15.682500,3621.92500
50%,27582.500000,47.000000,27.500000,21.970000,4249.39000
75%,38109.500000,73.000000,39.250000,27.492500,4797.17500
max,49354.000000,99.000000,49.000000,34.710000,6042.56000

In [9]:
data.head(5)

,Building Type,Square Footage,Number of Occupants,Appliances Used,Average Temperature,Day of Week,Energy Consumption
0,Residential,24563,15,4,28.52,Weekday,2865.57
1,Commercial,27583,56,23,23.07,Weekend,4283.80
2,Commercial,45313,4,44,33.56,Weekday,5067.83
3,Residential,41625,84,17,27.39,Weekend,4624.30
4,Residential,36720,58,47,17.08,Weekday,4820.59

In [14]:
data['Building Type']

0     Residential
1      Commercial
2      Commercial
3     Residential
4     Residential
         ...
95     Commercial
96    Residential
97     Commercial
98     Industrial
99    Residential
Name: Building Type, Length: 100, dtype: object

In [17]:
building_type_map = {'Residential':1,'Commercial':2,'Industrial':3}
day_map = {'Weekday':1,'Weekend':0}

In [18]:
data['Building Type'] = data['Building Type'].map(building_type_map)
data['Day of Week'] = data['Day of Week'].map(day_map)

In [21]:
y = data['Energy Consumption']

In [20]:
X= data.drop(columns='Energy Consumption')

In [24]:
X.head()

,Building Type,Square Footage,Number of Occupants,Appliances Used,Average Temperature,Day of Week
0,1,24563,15,4,28.52,1
1,2,27583,56,23,23.07,0
2,2,45313,4,44,33.56,1
3,1,41625,84,17,27.39,0
4,1,36720,58,47,17.08,1

In [25]:
y.head()

0    2865.57
1    4283.80
2    5067.83
3    4624.30
4    4820.59
Name: Energy Consumption, dtype: float64

# Used train test split to slice data into 20% for train 80% for test data

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the model

In [30]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

# Test the model

In [32]:
y_pred_train = model.predict(X_train)
y_pred_test = model.predict(X_test)

In [39]:
# Evaluate the model
mse_train = mean_squared_error(y_train, y_pred_train)
mse_test = mean_squared_error(y_test, y_pred_test)

In [36]:
print(f'MEAN SQUARE ERROR FOR TRAIN {mse_train}')
print(f'MEAN SQUARE ERROR FOR TEST {mse_test}')

MEAN SQUARE ERROR FOR TRAIN 0.00016846373971334655
MEAN SQUARE ERROR FOR TEST 0.00024993469774694735

In [40]:
print("Model Coefficients:", model.coef_)
print("Model Intercept:", model.intercept_)

Model Coefficients: [ 4.99996571e+02  4.99999063e-02  9.99992124e+00  1.99998503e+01
 -5.00011549e+00  5.00040236e+01]
Model Intercept: 1000.0175549671649